### ISSUE TITLE
Installing without composer

### ISSUE THREAD

**Issue by D0Gmatist** [PHPOffice/PHPWord#783] opened 2016-04-19 08:36 UTC
Tell me please. How to install without using the composer PHPword?

**Comment by AcademyLime** [comment] 2016-06-13 20:40
+1

**Comment by ComputerTinker** [comment] 2016-06-23 20:51
I would like to know if it's still possible to install without using composer as well. I forked PHPWord several months ago and made changes which still have not been merged into the main repo. A few days ago I sync'd my fork with upstream (preserving my changes) but doing so broke my library because the old autoloader file was deleted in favor of using composer. 

Now I'm in the position of needing to install composer at each site where I had previously installed this library. It also appears that in order for composer to see my fork of the library instead of the main branch, I'll need to publish my fork to packagelist.org and keep at least composer.json (possibly others?) permanently out of sync with upstream. Just started reading through the composer documentation, but right now this seems like extra hassle when it was working fine previously...

**Comment by josotoru** [comment] 2016-09-14 22:40
+1

**Comment by Alvalvar** [comment] 2016-09-23 18:42
+1

**Comment by camilofernandesalves** [comment] 2016-09-23 21:07
What's your problem with composer? 
With composer it's easier to manage updates from library.
It's not recommendable, install without composer.

**Comment by tcotys** [comment] 2016-10-12 15:22
Hi,
I know that composer is a better way to install and manage libraries,
but due to host limitation, I doesn't have ssh access to my website (only ftp access),
therefore, I'm not able install composer nor install composer libraries.
All I can do is to drag and drop files and manage everything manually
(which might not be the best way, I admit, but it's the only one for me)
Regards

Arnaud

**Comment by jarrettj** [comment] 2016-10-13 06:04
Dude you need to get off your shitty provider! asap. There are so many cool cloud offerings out there that give you root access to vm machines. Choose one. :)

**Comment by tcotys** [comment] 2016-10-13 08:37
I have my reason to keep this provider (quite good quality service, no need of credit card/paypal or any internet banking, nice privacy politics). I have also some budget limitation which forbid me to add the ssh option with the same provider.
Maybe I'm the only one in this case, maybe not.

(also sorry for possible confusion coming from my bad english)

**Comment by tcotys** [comment] 2016-10-14 07:35
Anyway, the ugly workaround I have found is to install PHPWord on my local machine using composer, then paste it on the server. It works (my local configuration is the same as the one of the website).

**Comment by MarkehMe** [comment] 2017-01-28 08:07
Also in the case that you're building add-ons for software that requires distributing.

It's very simple though.

Download PHPWord and run `composer install` on your local machine in the folder. Rename the folder from say `PHPWord-0.13.0` to `PHPWord` and put it into your project (in my case, this was `lib/PHPWord`.

Then you can include it like:
```php
include("lib/PHPWord/bootstrap.php");
```

The size of this library was 130mb for me - just take note of that!

**Closed** 2017-07-04 14:19 UTC

**Comment by vicluber** [comment] 2018-02-26 23:27
Composer is a fucking stupid lazy thing that never works

**Comment by abelcallejo** [comment] 2019-06-11 10:30
> Tell me please. How to install without using the composer PHPword?

If the problem is about the "slowness" of **Composer** then all you need is to install a plugin as stated in this [stackoverflow answer](https://stackoverflow.com/questions/28436237/why-is-php-composer-so-slow#38102206). I hope it helps for those who got frustrated.
