### ISSUE TITLE
HTML, putting a tag into a list item line causes list item text to disappear when writing to docx. Where can I find?

### ISSUE THREAD

**Issue by WriterStat** [PHPOffice/PHPWord#626] opened 2015-09-24 21:04 UTC
Hi reading in a html string with a tag in a list item `<li>` causes the text in that list item to disappear.

Instead of applying that tag to the list item text, such as bold or strong `<strong>`.

Unexpected error.

Not asking for a fix, just for a pointer or a leg up to where that might be handled in the code base, where I might look for it, so I can fix it.

I've added `<b>` and a few other things to HTML.php. Lists work fine, it just doesn't seem to like tags in them.  I'd like to update them.

Thanks!

Cheers,

-C

**Comment by Yrutan** [comment] 2015-11-27 04:30
I seems to be having the same problem. When I save a text from a web page to a Word document the items of a list with an additional tag are not read/saved. 

 Just to be sure it wasn't how I used it, I confirmed by changing the Sample_30_ReadHTML.php to include the situation and it does exactly what is described.

Any idea of what is causing it to do that ? 
Or of what would be the implications of changing it to make it work ?

**Comment by raf-sh** [comment] 2016-11-14 15:41
Can confirm, have same problem - if there are any tags inside <li></li> - there is no text in output docx on related lines

**Comment by ZombieBunny** [comment] 2017-08-03 06:59
I seem to have come across the same issue. 
Any tags within a list item tag renders that list item empty when its converted into a word docx file. 
Iv had to remove all other tags between li tags to get the list to display again, this is how i do it:

      `$html = preg_replace_callback('#(<li[^>]*>)(.+?)(</li>)#is', function($m){
            return($m[1].strip_tags($m[2]).$m[3]);
        }, $html);`

I hope this helps as a workaround.

**Comment by troosan** [comment] 2017-12-25 17:06
this has been partially fixed in [milestone v0.14.0](https://github.com/PHPOffice/PHPWord/milestone/17), to formatting will be lost but the text will at least be kept.

**Closed by troosan** 2017-12-25 17:06 UTC
