### ISSUE TITLE
Problems with & symbol

### ISSUE THREAD

**Issue by luckyr13** [PHPOffice/PHPWord#938] opened 2016-11-10 04:31 UTC
Hello, using PhpWord I found that if you place a symbol & inside of a cell you can corrupt the docx file ... can someone help to explain or confirm this issue please? 

```
$table = $this->main_section->addTable($this->tstyle[0]);
$row1 = $table->addRow();
$row1_cel1 = $row1->addCell($TABLE_COL1_WIDTH, $tbl_style);
// If you place an ampersand symbol, the docx gets corrupted
$row1_cel1->addText('(If & Then)', array('italic' => true), $cell_textcenter);

```

**Comment by raf-sh** [comment] 2016-11-14 15:21
please have a look at official documentation - http://phpword.readthedocs.io/en/latest/general.html#output-escaping

phpWord has build-in escaping - it solves this kind of issues

**Comment by luckyr13** [comment] 2016-11-14 20:31
thank you very much! I didn't notice that phpWord had this build-in.

**Comment by cookiekiller** [comment] 2016-12-13 15:00
@Progi1984 we can close this one

**Closed** 2016-12-13 15:59 UTC
Labels: Documentation

**Comment by eulemis** [comment] 2018-05-19 15:25
Hello, I have a problem printing some references the issue is that it does, but when downloading the file the word tells me that the content of the file is damaged if I give it that I accept the risks it opens me without problems how to correct this problem? oh my code is this: 
           $textrun = $section->addTextRun();
            $textrun->addText($num.'.'.$texto1);
            $textrun->addText(htmlspecialchars_decode($titulo), ['italic' => true]);
            $textrun->addText(htmlspecialchars_decode($texto2);
but if I remove these lines does not give me the warning
