### ISSUE TITLE
Convert DOCX to ODT

### ISSUE THREAD

**Issue by ImmanuelJL** [PHPOffice/PHPWord#1081] opened 2017-06-22 08:52 UTC
hi, the goal is i want to convert my docx files into ODT. I try this:

$phpWord = new \PhpOffice\PhpWord\PhpWord();

//Open template and save it as docx
$document = $phpWord->loadTemplate('yourtemplate.docx');
$document->saveAs('temp.docx');

//Load temp file
$phpWord = \PhpOffice\PhpWord\IOFactory::load('temp.docx'); 

//Save it
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord , 'ODText');
$xmlWriter->save('result.odt');  

The file is converted but i cant open the odt file...

**Comment by troosan** [comment] 2017-06-26 23:24
Can you upload a sample document?
It is hard to debug with so little info. As far as I could try it worked.

**Comment by ImmanuelJL** [comment] 2017-06-27 08:56
Hi, can you share your working code here?  I really need to convery ny docx files into odt.  Thanks

**Comment by ImmanuelJL** [comment] 2017-06-27 08:57
I really need to convert my docx files into odt

**Comment by troosan** [comment] 2017-06-27 18:21
I used exactly your code, I guess it depends on the document you are trying to load.
Be aware that the IOFactory::load will only parse features it "knows", everything else will be lost, can you share a docx file that fails to be converted?

**Comment by ImmanuelJL** [comment] 2017-06-28 02:52
Hi, thanks for your info. I am just using a simple docx files, here i attached it on dropbox. Thank you https://www.dropbox.com/s/iza1tvypypcpzs3/test.docx?dl=0

**Comment by troosan** [comment] 2017-06-28 21:17
I tried with your document. The resulting file can be opened but the formatting is not the same at all.
I get one "test" per line ...
I actually get the same result when writing the document to docx, which indicates that the problem is in the load.
I do not have an exhaustive list of features that are getting "read" correctly, I guess the load functionality need some serious fixing, but I do not have any time for that right now.

**Comment by ImmanuelJL** [comment] 2017-06-29 03:02
Hi, i try it by myself and yes it depends on the document i trying to load. Can you help me how to solve this? There is a better way so i can convert the whole document?

**Comment by troosan** [comment] 2017-07-04 20:36
@ImmanuelJL FYI, a fix for this issue has been merged to the development branch. It will be part of the next 0.14 version

**Closed by troosan** 2017-07-04 20:36 UTC

**Comment by ImmanuelJL** [comment] 2017-07-05 02:40
Hi @troosan , thanks for your info !
