### ISSUE TITLE
Even and odd page headers

### ISSUE THREAD

**Issue by w1ck3dg0ph3r** [PHPOffice/PHPWord#674] opened 2015-12-01 14:09 UTC
When even and odd page headers are set up, only odd one seem to appear in Word2007 writer due to missing `<w:evenAndOddHeaders/>` in `/word/settings.xml`.

**Comment by jaff521** [comment] 2016-12-02 08:20
hello, I am using PHPWord 12.0, and meet a problem of creating even and odd page footers,  I tried to make different footers, but failed, would you please to help me, thanks,  my codes are below:

$footer = $section->addFooter();
$footer->addPreserveText('{PAGE}', null, ['align' => 'right']);

$footerEven = $section->addFooter('even');
$footerEven->addPreserveText('{PAGE}' null, ['align' => 'left']);

**Comment by ctrlaltca** [comment] 2017-08-02 08:26
I guess this is a duplicate of the closed #981

**Comment by troosan** [comment] 2017-12-25 17:08
fixed in 0.14

**Closed by troosan** 2017-12-25 17:08 UTC
