### ISSUE TITLE
Vector images in phpWord

### ISSUE THREAD

**Issue by landerdominguez** [PHPOffice/PHPWord#1576] opened 2019-02-14 08:29 UTC
Hi!

I have done an application using phpWord to get my company manuals, but I have an issue with vector images. Engineering area gives me the images in vector format (wmf/emf) and I can't add them to the manuals.

I have tried to convert to png, but I loose a lot of image quality. 

Is there any option to add these kind of images?

Thanks in advance.

**Comment by mynukeviet** [comment] 2019-05-22 21:55
Up

**Comment by Progi1984** [comment] 2023-09-26 17:43
Duplicate of #1480

**Closed by Progi1984** 2023-09-26 17:43 UTC
