### ISSUE TITLE
RTF to DOCX convert

### ISSUE THREAD

**Issue by mdeprezzo** [PHPOffice/PHPWord#1175] opened 2017-10-27 09:12 UTC
It's possible to convert rtf document to docx ?

**Comment by FBnil** [comment] 2017-10-27 12:30
You need to use the IOFactory::load() function to read it in, and the IOFactory::createWriter() to write it out, and you can convert from a few supported formats. Make sure that the php user CAN read the inputfile and can write into the output directory
```
$testDoc = storage_path($input_rtf);
$phpWord = \PhpOffice\PhpWord\IOFactory::load($testDoc, 'RTF');

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save($output_docx);
```
however, the `\'hh` (hexadecimal notation) in RTF is not being read yet in 0.13.0, thus, they will not be there in the docx :(  
For a good replacement, use the commandline version of oowriter. (examples given in the other replies)

**Comment by mdeprezzo** [comment] 2017-10-27 12:35
And i notice that there's something else like this message:

```Illegal string offset 'w:compatSetting'

**Comment by FBnil** [comment] 2017-10-27 19:57
This is too little information to know what the issue is. Can you elaborate?

**Comment by mdeprezzo** [comment] 2017-10-27 20:19
I need to test again that call, because for now i've fixed my problem with the convertion of the rtf file with libreoffice wrapper package that execute the command line convertion. But is a lot of work to do on server side, if the users become more and more.

**Comment by mdeprezzo** [comment] 2017-10-28 17:20
> This is too little information to know what the issue is. Can you elaborate

When i use $objwriter->save() method, i got that error, in Settings.php on line 173.

**Comment by troosan** [comment] 2017-11-06 16:16
@mdeprezzo please try with the latest development version (0.14) where this is fixed.
If OK, can you please close the issue?

**Comment by mdeprezzo** [comment] 2017-11-06 17:12
Sure, i'll try as soon as possible.

**Comment by mdeprezzo** [comment] 2017-12-19 14:03
@troosan i0m trying to install v0.14 but with composer i've an error:

>   Problem 1
    - The requested package phpoffice/phpword v0.14.* exists as phpoffice/phpword[0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, dev-develop, dev-master, v0.12.1, v0.13.0] but these are rejected by your constraint.

i need use dev-develop version ?

**Comment by troosan** [comment] 2017-12-19 20:31
indeed, 0.14 is not released yet, you should use dev-develop.
The RTF reader is probably not very complete, so you are probably loosing some formatting when parsing the rtf doc.

**Comment by netinhoteixeira** [comment] 2018-04-05 00:34
When it error happens:
`[05-Apr-2018 00:29:28 UTC] PHP Warning:  Illegal string offset 'w:compatSetting' in /Users/francisco/Customers/br.com.institutototum/certificacao/admin-api/vendor/phpoffice/phpword/src/PhpWord/Writer/Word2007/Part/Settings.php on line 177`

Solved with:
```
            if (is_string($this->settings['w:compat'])) {
                $this->settings['w:compat'] = array();
            }
```

in `private function getCompatibility()`.

So, final code:
```
    /**
     * Get compatibility setting.
     *
     * @return void
     */
    private function getCompatibility()
    {
        $compatibility = $this->getParentWriter()->getPhpWord()->getCompatibility();
        if ($compatibility->getOoxmlVersion() !== null) {
            if (is_string($this->settings['w:compat'])) {
                $this->settings['w:compat'] = array();
            }

            $this->settings['w:compat']['w:compatSetting'] = array('@attributes' => array(
                'w:name'    => 'compatibilityMode',
                'w:uri'     => 'http://schemas.microsoft.com/office/word',
                'w:val'     => $compatibility->getOoxmlVersion(),
            ));
        }
    }
```

**Comment by e1sep0** [comment] 2019-04-04 13:58
So i can`t convert RTF to docx ?

**Comment by mdeprezzo** [comment] 2019-04-05 10:59
@e1sep0 it is a fairly vast and complex discourse. It depends on many factors, related to formatting. For now I solved using "calibre" from the command line

**Closed** 2019-04-05 11:00 UTC
