### ISSUE TITLE
PHP 7: Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name

### ISSUE THREAD

**Issue by btaens** [PHPOffice/PHPWord#736] opened 2016-02-22 10:15 UTC
The String class name is occupied in base PHP 7, therefore the class `String` throws an error.

**Comment by fisharebest** [comment] 2016-03-02 15:58
Duplicate of #642, #730, #732, etc.

Already fixed, but not released, so specify `"php-office/php-word": "dev-develop"` in your composer.json

**Comment by garethellis36** [comment] 2016-03-23 17:51
When is the release due? I do not particularly want to use a develop branch release in production.

**Comment by MrMitch** [comment] 2016-07-25 15:09
any news on this ?

**Comment by MicBehrens** [comment] 2016-08-09 13:01
This should be prioritized.

**Comment by kehh** [comment] 2016-08-17 01:24
This is included in https://github.com/PHPOffice/PHPWord/releases/tag/v0.13.0

**Comment by agwidarsito** [comment] 2016-09-07 05:27
Is this included in a more stable release other than dev-develop?

**Comment by clemens-tolboom** [comment] 2017-12-12 15:57
This works for v0.13.0.

@agwidarsito I myself cannot use develop version with Drupal but you can pin a dev version too using a commit version

```
"require": {
        "phpoffice/phpword": "dev-develop#fd156bf12a6d"
}
```

**Closed** 2017-12-25 18:39 UTC

**Comment by agwidarsito** [comment] 2018-01-09 01:33
@clemens-tolboom Awesome, good to know. Thanks! :)
